// frontend/src/components/reports/ReportDetails.jsx
import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import reportService from "../../services/reportService.js";

export default function ReportDetails() {
  const { id } = useParams();
  const [report, setReport] = useState(null);

  useEffect(() => {
    const load = async () => {
      try {
        const { data } = await reportService.getReportById(id);
        setReport(data.report);
      } catch (err) {
        console.error("Failed to load report", err);
      }
    };
    load();
  }, [id]);

  if (!report) return <p>Loading...</p>;

  return (
    <div>
      <h1 className="text-2xl font-bold mb-4">Report Details</h1>
      <p>Generated by: {report.generatedBy?.name} ({report.generatedBy?.email})</p>
      <p>Generated at: {new Date(report.generatedDate).toLocaleString()}</p>
      <p>Total: {report.totalComplaints} • Resolved: {report.resolvedCount} • Pending: {report.pendingCount}</p>

      <div className="mt-6 grid md:grid-cols-2 gap-4">
        {report.complaints.map((c) => (
          <div key={c._id} className="bg-white p-3 rounded shadow">
            <h3 className="font-semibold">{c.type} • {c.status}</h3>
            <p className="text-sm text-gray-600">{c.description}</p>
            <p className="text-xs text-gray-400 mt-2">By: {c.citizen?.name} • {c.citizen?.email}</p>
            {c.photo && <img src={c.photo} alt="photo" className="mt-2 rounded w-full h-40 object-cover" />}
          </div>
        ))}
      </div>
    </div>
  );
}
